In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv("/content/Dataset .csv")


In [ ]:
df

Restaurant ID           Restaurant Name  Country Code              City  \
0           6317637          Le Petit Souffle           162       Makati City   
1           6304287          Izakaya Kikufuji           162       Makati City   
2           6300002    Heat - Edsa Shangri-La           162  Mandaluyong City   
3           6318506                      Ooma           162  Mandaluyong City   
4           6314302               Sambo Kojin           162  Mandaluyong City   
...             ...                       ...           ...               ...   
9546        5915730               Naml۱ Gurme           208         ��stanbul   
9547        5908749              Ceviz A��ac۱           208         ��stanbul   
9548        5915807                     Huqqa           208         ��stanbul   
9549        5916112               A���k Kahve           208         ��stanbul   
9550        5927402  Walter's Coffee Roastery           208         ��stanbul   

                                                Address  \
0     Third Floor, Century City Mall, Kalayaan Avenu...   
1     Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2     Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3     Third Floor, Mega Fashion Hall, SM Megamall, O...   
4     Third Floor, Mega Atrium, SM Megamall, Ortigas...   
...                                                 ...   
9546  Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...   
9547  Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...   
9548  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9549  Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...   
9550  Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...   

                                        Locality  \
0      Century City Mall, Poblacion, Makati City   
1     Little Tokyo, Legaspi Village, Makati City   
2     Edsa Shangri-La, Ortigas, Mandaluyong City   
3         SM Megamall, Ortigas, Mandaluyong City   
4         SM Megamall, Ortigas, Mandaluyong City   
...                                          ...   
9546                                    Karak�_y   
9547                                   Ko��uyolu   
9548                                 Kuru�_e��me   
9549                                 Kuru�_e��me   
9550                                        Moda   

                                       Locality Verbose   Longitude  \
0     Century City Mall, Poblacion, Makati City, Mak...  121.027535   
1     Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101   
2     Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831   
3     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475   
4     SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508   
...                                                 ...         ...   
9546                                Karak�_y, ��stanbul   28.977392   
9547                               Ko��uyolu, ��stanbul   29.041297   
9548                             Kuru�_e��me, ��stanbul   29.034640   
9549                             Kuru�_e��me, ��stanbul   29.036019   
9550                                    Moda, ��stanbul   29.026016   

       Latitude                          Cuisines  ...          Currency  \
0     14.565443        French, Japanese, Desserts  ...  Botswana Pula(P)   
1     14.553708                          Japanese  ...  Botswana Pula(P)   
2     14.581404  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)   
3     14.585318                   Japanese, Sushi  ...  Botswana Pula(P)   
4     14.584450                  Japanese, Korean  ...  Botswana Pula(P)   
...         ...                               ...  ...               ...   
9546  41.022793                           Turkish  ...  Turkish Lira(TL)   
9547  41.009847   World Cuisine, Patisserie, Cafe  ...  Turkish Lira(TL)   
9548  41.055817            Italian, World Cuisine  ...  Turkish Lira(TL)   
9549  41.057979                   Restaurant Cafe  ...  Turkish Lira(TL)   
9550  40.9

In [ ]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [ ]:
# Another correct way using the columns keyword argument explicitly
df = df.drop(columns=[ 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude',
       'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
        'Rating color', 'Rating text',
       'Votes'], axis=1)

In [ ]:
df

Restaurant ID           Restaurant Name  \
0           6317637          Le Petit Souffle   
1           6304287          Izakaya Kikufuji   
2           6300002    Heat - Edsa Shangri-La   
3           6318506                      Ooma   
4           6314302               Sambo Kojin   
...             ...                       ...   
9546        5915730               Naml۱ Gurme   
9547        5908749              Ceviz A��ac۱   
9548        5915807                     Huqqa   
9549        5916112               A���k Kahve   
9550        5927402  Walter's Coffee Roastery   

                              Cuisines  Average Cost for two  Price range  \
0           French, Japanese, Desserts                  1100            3   
1                             Japanese                  1200            3   
2     Seafood, Asian, Filipino, Indian                  4000            4   
3                      Japanese, Sushi                  1500            4   
4                     Japanese, Korean                  1500            4   
...                                ...                   ...          ...   
9546                           Turkish                    80            3   
9547   World Cuisine, Patisserie, Cafe                   105            3   
9548            Italian, World Cuisine                   170            4   
9549                   Restaurant Cafe                   120            4   
9550                              Cafe                    55            2   

      Aggregate rating  
0                  4.8  
1                  4.5  
2                  4.4  
3                  4.9  
4                  4.8  
...                ...  
9546               4.1  
9547               4.2  
9548               3.7  
9549               4.0  
9550               4.0  

[9551 rows x 6 columns]

In [ ]:
# Generate dummy variables for 'Cuisines'
cuisines_dummies = pd.get_dummies(df['Cuisines'], drop_first=True)

# Concatenate the dummy variables to the original DataFrame
df = pd.concat([df, cuisines_dummies], axis=1)

# Drop the original 'Cuisines' column if it is no longer needed
df.drop('Cuisines', axis=1, inplace=True)


In [ ]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Average Cost for two',
       'Price range', 'Aggregate rating', 'Afghani, Mughlai, Chinese',
       'Afghani, North Indian', 'Afghani, North Indian, Pakistani, Arabian',
       'African', 'African, Portuguese',
       ...
       'Turkish, Arabian, Middle Eastern',
       'Turkish, Arabian, Moroccan, Lebanese',
       'Turkish, Mediterranean, Middle Eastern', 'Vietnamese',
       'Vietnamese, Fish and Chips', 'Western, Asian, Cafe',
       'Western, Fusion, Fast Food', 'World Cuisine',
       'World Cuisine, Mexican, Italian', 'World Cuisine, Patisserie, Cafe'],
      dtype='object', length=1829)

In [ ]:
X = df[['Average Cost for two','Restaurant ID', 'Price range', 'Aggregate rating'] + list(cuisines_dummies.columns)]
y=df[['Restaurant Name']]

In [ ]:
X.shape

(9551, 1828)

In [ ]:
y.shape

(9551, 1)

In [ ]:
df

Restaurant ID           Restaurant Name  Average Cost for two  \
0           6317637          Le Petit Souffle                  1100   
1           6304287          Izakaya Kikufuji                  1200   
2           6300002    Heat - Edsa Shangri-La                  4000   
3           6318506                      Ooma                  1500   
4           6314302               Sambo Kojin                  1500   
...             ...                       ...                   ...   
9546        5915730               Naml۱ Gurme                    80   
9547        5908749              Ceviz A��ac۱                   105   
9548        5915807                     Huqqa                   170   
9549        5916112               A���k Kahve                   120   
9550        5927402  Walter's Coffee Roastery                    55   

      Price range  Aggregate rating  Afghani, Mughlai, Chinese  \
0               3               4.8                      False   
1               3               4.5                      False   
2               4               4.4                      False   
3               4               4.9                      False   
4               4               4.8                      False   
...           ...               ...                        ...   
9546            3               4.1                      False   
9547            3               4.2                      False   
9548            4               3.7                      False   
9549            4               4.0                      False   
9550            2               4.0                      False   

      Afghani, North Indian  Afghani, North Indian, Pakistani, Arabian  \
0                     False                                      False   
1                     False                                      False   
2                     False                                      False   
3                     False                                      False   
4                     False                                      False   
...                     ...                                        ...   
9546                  False                                      False   
9547                  False                                      False   
9548                  False                                      False   
9549                  False                                      False   
9550                  False                                      False   

      African  African, Portuguese  ...  Turkish, Arabian, Middle Eastern  \
0       False                False  ...                             False   
1       False                False  ...                             False   
2       False                False  ...                             False   
3       False                False  ...                             False   
4       False                False  ...                             False   
...       ...                  ...  ...                               ...   
9546    False                False  ...                             False   
9547    False                False  ...                             False   
9548    False                False  ...                             False   
9549    False                False  ...                             False   
9550    False                False  ...                             False   

      Turkish, Arabian, Moroccan, Lebanese  \
0                                    False   
1                                    False   
2                                    False   
3                                    False   
4                                    False   
...                                    ...   
9546                                 False   
9547                                 False   
9548                                 False   
9549                                 False   
9550                                 Fal

In [ ]:
df.columns

Index(['Restaurant ID', 'Restaurant Name', 'Average Cost for two',
       'Price range', 'Aggregate rating', 'Afghani, Mughlai, Chinese',
       'Afghani, North Indian', 'Afghani, North Indian, Pakistani, Arabian',
       'African', 'African, Portuguese',
       ...
       'Turkish, Arabian, Middle Eastern',
       'Turkish, Arabian, Moroccan, Lebanese',
       'Turkish, Mediterranean, Middle Eastern', 'Vietnamese',
       'Vietnamese, Fish and Chips', 'Western, Asian, Cafe',
       'Western, Fusion, Fast Food', 'World Cuisine',
       'World Cuisine, Mexican, Italian', 'World Cuisine, Patisserie, Cafe'],
      dtype='object', length=1829)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [93]:
# Predict on the test set
y_test_pred = classifier.predict(x_test)


In [99]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [100]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_test_pred)
print("Accuracy:", accuracy)


Accuracy: 0.1076214405360134


In [111]:
# Print confusion matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
